# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: whisper.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'whisper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwhisper.proto\x12\x06\x61sr.v1\"\x8f\x01\n\x10StreamingRequest\x12\'\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x15.asr.v1.SessionConfigH\x00\x12#\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x12.asr.v1.AudioChunkH\x00\x12\"\n\x07\x63ontrol\x18\x03 \x01(\x0b\x32\x0f.asr.v1.ControlH\x00\x42\t\n\x07payload\"}\n\rSessionConfig\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x17\n\x0f\x65nable_partials\x18\x04 \x01(\x08\x12\x12\n\nsession_id\x18\x05 \x01(\t\"(\n\nAudioChunk\x12\r\n\x05pcm16\x18\x01 \x01(\x0c\x12\x0b\n\x03seq\x18\x02 \x01(\r\"T\n\x07\x43ontrol\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.asr.v1.Control.Type\"%\n\x04Type\x12\x07\n\x03\x45OS\x10\x00\x12\t\n\x05\x46LUSH\x10\x01\x12\t\n\x05RESET\x10\x02\"D\n\x08WordInfo\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x15\n\rstart_time_ms\x18\x02 \x01(\x02\x12\x13\n\x0b\x65nd_time_ms\x18\x03 \x01(\x02\"\xb0\x01\n\x11StreamingResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x1f\n\x05words\x18\x05 \x03(\x0b\x32\x10.asr.v1.WordInfo\x12\x11\n\tstability\x18\x06 \x01(\x02\x12\x10\n\x08replaces\x18\x07 \x01(\r\x12\r\n\x05\x65rror\x18\x08 \x01(\t2T\n\x03\x41sr\x12M\n\x12StreamingRecognize\x12\x18.asr.v1.StreamingRequest\x1a\x19.asr.v1.StreamingResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'whisper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMINGREQUEST']._serialized_start=26
  _globals['_STREAMINGREQUEST']._serialized_end=169
  _globals['_SESSIONCONFIG']._serialized_start=171
  _globals['_SESSIONCONFIG']._serialized_end=296
  _globals['_AUDIOCHUNK']._serialized_start=298
  _globals['_AUDIOCHUNK']._serialized_end=338
  _globals['_CONTROL']._serialized_start=340
  _globals['_CONTROL']._serialized_end=424
  _globals['_CONTROL_TYPE']._serialized_start=387
  _globals['_CONTROL_TYPE']._serialized_end=424
  _globals['_WORDINFO']._serialized_start=426
  _globals['_WORDINFO']._serialized_end=494
  _globals['_STREAMINGRESPONSE']._serialized_start=497
  _globals['_STREAMINGRESPONSE']._serialized_end=673
  _globals['_ASR']._serialized_start=675
  _globals['_ASR']._serialized_end=759
# @@protoc_insertion_point(module_scope)
