services:

  ksql-server:
    image: confluentinc/cp-ksqldb-server:7.2.15
    hostname: ksql-server
    container_name: ksql-server
    depends_on:
      - kafka
      - connect
    ports:
      - "${KSQL_SERVER_PORT}:8088"
    networks:
      - localnet
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "kafka:29092"
      KSQL_HOST_NAME: ksql-server
      KSQL_APPLICATION_ID: "cp-all-in-one"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"

  ksql-cli:
    image: confluentinc/cp-ksqldb-cli:7.2.15
    container_name: ksql-cli
    depends_on:
      - kafka
      - connect
      - ksql-server
    entrypoint: /bin/sh
    tty: true
    networks:
      - localnet

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.2.15
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - ${REST_PROXY_PORT}:8082
    hostname: rest-proxy
    container_name: rest-proxy
    networks:
      - localnet
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.2.15
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
      - connect
      - ksql-server
    ports:
      - "${CONTROL_CENTER_PORT}:9021"
    networks:
      - localnet
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'

      CONTROL_CENTER_CONNECT_CONNECT_CLUSTER: 'http://connect:8083'

      CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"

      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://ksql-server:8088"

      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
  


networks:
  localnet: {}
